### PR TITLE
revise: drive-3, macos shortcut

### PR DESCRIPTION
**Pull request by djdjz7**

### CODE REVIEW

**Comment by leavelet** [comment]
@xuehaonan27 试一下看看？我没有mac了，感觉还是怪怪的

**Comment by 000lbh** [comment]
Your commit email do not match your github account's email addresses. You can change your commit email using `git config user.email admin@example.com` (add `--global` to make changes global effective, or changes only take effect on current git repository) or add other email addresses to your github account

**Review by xuehaonan27 — APPROVED** [review]
Correct

**Review by leavelet — APPROVED** [review]
LGTM as Haonan has tested it

**Pull request merged**
